library("ggplot2")
library("caret")
data = read.csv("train.csv")
View(data)
range(data$x)
range(data$y)
ggplot(data, aes(x, y)) + geom_line() + scale_x_continuous(limits = c(0, 4000)) +scale_y_continuous(limits = c(0,130))
sum(data$x) < 0
sum(data$y) < 0
data$x <- log(abs(data$x))
data$y <- log(abs(data$y))
data$x <- as.integer(data$x)
data$y <- as.integer(data$y)
which(is.na(data$x))
data$x[which(is.na(data$x))] <- round(median(data$x, na.rm = TRUE))
which(is.na(data$y))
data$y[which(is.na(data$y))] <- round(median(data$y, na.rm = TRUE))
range(data$x)
range(data$y)
ggplot(data, aes(x, y)) + geom_point()
linearmodel = lm(data$y ~ data$x, data)
summary(linearmodel)
test = read.csv("test.csv")
View(test)
range(test$x)
range(test$y)
ggplot(test, aes(x, y)) + geom_line() + scale_x_continuous(limits = c(0, 100)) +scale_y_continuous(limits = c(-4,110))
test$x <- log(abs(test$x))
test$y <- log(abs(test$y))
test$x <- as.integer(test$x)
test$y <- as.integer(test$y)
which(is.na(test$x))
test$x[which(is.na(test$x))] <- round(median(test$x, na.rm = TRUE))
which(is.na(test$y))
test$y[which(is.na(test$y))] <- round(median(test$y, na.rm = TRUE))
range(test$x)
range(test$y)
ggplot(test, aes(x, y)) + geom_point() + scale_x_continuous(limits = c(0, 4)) +scale_y_continuous(limits = c(-1,4))
testmodel <- predict(linearmodel, newdata = test)
summary(testmodel)
